//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelForm.PersonelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personel", Namespace="http://schemas.datacontract.org/2004/07/PersonelManagerLibrary")]
    [System.SerializableAttribute()]
    public partial class Personel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeslekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maas {
            get {
                return this.MaasField;
            }
            set {
                if ((object.ReferenceEquals(this.MaasField, value) != true)) {
                    this.MaasField = value;
                    this.RaisePropertyChanged("Maas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Meslek {
            get {
                return this.MeslekField;
            }
            set {
                if ((object.ReferenceEquals(this.MeslekField, value) != true)) {
                    this.MeslekField = value;
                    this.RaisePropertyChanged("Meslek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sehir {
            get {
                return this.SehirField;
            }
            set {
                if ((object.ReferenceEquals(this.SehirField, value) != true)) {
                    this.SehirField = value;
                    this.RaisePropertyChanged("Sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelNo {
            get {
                return this.TelNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNoField, value) != true)) {
                    this.TelNoField = value;
                    this.RaisePropertyChanged("TelNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonelService.IPersonelService")]
    public interface IPersonelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonelService/Add", ReplyAction="http://tempuri.org/IPersonelService/AddResponse")]
        bool Add(PersonelForm.PersonelService.Personel personel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonelService/Delete", ReplyAction="http://tempuri.org/IPersonelService/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonelService/Update", ReplyAction="http://tempuri.org/IPersonelService/UpdateResponse")]
        bool Update(PersonelForm.PersonelService.Personel personel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonelService/GetById", ReplyAction="http://tempuri.org/IPersonelService/GetByIdResponse")]
        PersonelForm.PersonelService.Personel GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonelService/GetAll", ReplyAction="http://tempuri.org/IPersonelService/GetAllResponse")]
        System.Data.DataTable GetAll();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonelServiceChannel : PersonelForm.PersonelService.IPersonelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonelServiceClient : System.ServiceModel.ClientBase<PersonelForm.PersonelService.IPersonelService>, PersonelForm.PersonelService.IPersonelService {
        
        public PersonelServiceClient() {
        }
        
        public PersonelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(PersonelForm.PersonelService.Personel personel) {
            return base.Channel.Add(personel);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public bool Update(PersonelForm.PersonelService.Personel personel) {
            return base.Channel.Update(personel);
        }
        
        public PersonelForm.PersonelService.Personel GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Data.DataTable GetAll() {
            return base.Channel.GetAll();
        }
    }
}
